# Generated by Django 6.0 on 2026-04-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistex', '0002_estudiante_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='regla',
            name='fuente_bibliografica',
            field=models.CharField(blank=True, max_length=300, verbose_name='Fuente bibliográfica'),
        ),
    ]
