# Generated by Django 6.0 on 2026-04-29 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistex', '0003_regla_fuente_bibliografica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('crear', 'Creación'), ('editar', 'Edición'), ('eliminar', 'Eliminación'), ('evaluar', 'Evaluación'), ('respaldo', 'Respaldo de BD'), ('restaurar', 'Restauración de BD'), ('toggle', 'Cambio de estado')], max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log del Sistema',
                'verbose_name_plural': 'Logs del Sistema',
                'ordering': ['-fecha'],
            },
        ),
    ]
